[package]
name = "mashlife"
version = "0.1.0"
edition = "2021"

[dependencies]
zwohash = { version = "0.1.2", default-features = false }
anyhow = "1"

[dev-dependencies]
structopt = { version = "0.3", default-features = false }
png = "0.17.2"
